######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 1 00:48:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QtHello.cpp
